
- name: Create necessary directories
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ cloudfront_build_dir }}"
    - "{{ cloudfront_template_dir }}"

- name: Template CloudFront repo
  template:
    src: "cloudfront.j2.json"
    dest: "{{ playbook_dir }}/{{ cloudfront_template_dir }}/{{ cloudfront_template_name }}"

- name: Show template
  shell: "cat {{ playbook_dir }}/{{ cloudfront_template_dir }}/{{ cloudfront_template_name }}"

- name: Create CloudFront repo stack (security token)
  cloudformation:
    region: "{{ cloudfront_region }}"
    stack_name: "{{ cloudfront_stack_name }}"
    state: "{{ cloudfront_stack_state|default('present') }}"
    template: "{{ playbook_dir }}/{{ cloudfront_template_dir }}/{{ cloudfront_template_name }}"
    tags: "{{ cloudfront_tags }}"
    security_token: "{{ cloudfront_security_token }}"
  register: cloudfront_stack
  when: cloudfront_security_token is defined

- name: Create CloudFront repo stack (no security token)
  cloudformation:
    region: "{{ cloudfront_region }}"
    stack_name: "{{ cloudfront_stack_name }}"
    state: "{{ cloudfront_stack_state|default('present') }}"
    template: "{{ playbook_dir }}/{{ cloudfront_template_dir }}/{{ cloudfront_template_name }}"
    tags: "{{ cloudfront_tags }}"
  register: cloudfront_stack
  when: cloudfront_security_token is not defined
